import '@fontsource-variable/dm-sans';
import '@fontsource-variable/noto-sans-kr';
import {initialState,topicNames,hasAccess,questionBank,selectQuiz,scoreAnswer,applyResult,purchase,reviewQuestion} from './core.js';
import {connection,demoState,saveDemo,resetDemo,emptyState,initialize,authenticate,signOut,api,uploadPDF} from './client.js';
let state=demoState();let session=null,lastResult=null,active='dashboard',selectedCourse='os',menuOpen=false;
const app=document.querySelector('#app'),modal=document.querySelector('#modal');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=(name,size=20)=>{const paths={grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',book:'<path d="M4 4h6a3 3 0 0 1 3 3v14a4 4 0 0 0-4-3H4zM13 7a3 3 0 0 1 3-3h5v14h-4a4 4 0 0 0-4 3"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',spark:'<path d="m12 3 2.8 6.2L21 12l-6.2 2.8L12 21l-2.8-6.2L3 12l6.2-2.8z"/>',link:'<path d="m10 13 4-4M8 15l-1 1a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0M14 9l1-1a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6zM8 12l3 3 5-6"/>',plus:'<path d="M12 5v14M5 12h14"/>',file:'<path d="M14 3H5v18h14V8zM14 3v5h5M8 12h8M8 16h6"/>',check:'<path d="m5 12 4 4L19 6"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',upload:'<path d="M12 16V3m-4 4 4-4 4 4M4 15v6h16v-6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',target:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',cap:'<path d="m2 9 10-5 10 5-10 5zM6 12v5c3 3 9 3 12 0v-5M22 9v8"/>'};return `<svg aria-hidden="true" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">${paths[name]||paths.book}</svg>`;};
const real=()=>Boolean(connection.user);
const topicsFor=c=>c?.topics||topicNames(c?.id);
let busy=false;
const current=()=>state.courses.find(c=>c.id===selectedCourse)||state.courses[0];
const btn=(label,action,cls='primary',attrs='')=>`<button class="btn ${cls}" data-action="${action}" ${attrs}>${label}</button>`;
function toast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('visible'),3600);}
function nav(id){active=id;menuOpen=false;render();window.scrollTo({top:0,behavior:'instant'});}
function dialog(content){modal.innerHTML=`<button class="dialog-close" data-action="close-dialog" aria-label="닫기">${icon('close')}</button>${content}`;modal.showModal();}
function courseTile(c){const n=questionBank(state,c.id).length,avg=Math.round(c.mastery.reduce((a,b)=>a+b,0)/Math.max(1,c.mastery.length)*100);return `<article class="course-card"><div class="row between"><span class="course-icon ${c.color}">${icon('book',26)}</span><span class="badge ${hasAccess(state,c)?'green':''}">${real()?'파일럿 무료':hasAccess(state,c)?'체험 이용 중':'이용권 필요'}</span></div><div class="course-title"><span class="eyebrow">${esc(c.code)} · ${esc(c.exam)}</span><h3>${esc(c.name)}</h3><p>${esc(c.professor)} · ${real()?'내 과목':'샘플 과목'}</p></div><div class="course-meta"><span>${icon('file',16)} 교안 ${c.materials.length}</span><span>검수 문항 ${n}</span></div><div class="row between small"><span>개념 숙련도</span><strong>${avg}%</strong></div><div class="progress"><i style="width:${avg}%"></i></div><button class="course-open" data-action="course" data-course="${c.id}">학습 공간 열기</button></article>`;}
function weakList(c,limit=5){return topicsFor(c).map((name,i)=>({name,i,m:c.mastery[i]})).sort((a,b)=>a.m-b.m).slice(0,limit).map(t=>`<div class="topic-row"><div><strong>${esc(t.name)}</strong><span>${t.m<.6?'한 번 더 확인해요':'잘 이해하고 있어요'}</span></div><div class="topic-meter"><div class="progress ${t.m<.6?'orange':''}"><i style="width:${Math.round(t.m*100)}%"></i></div><b>${Math.round(t.m*100)}%</b></div></div>`).join('');}
function dashboard(){if(!state.courses.length)return emptyDashboard();const c=current(),count=state.history.length,weak=state.courses.reduce((n,c)=>n+c.mastery.filter(x=>x<.6).length,0);return `<section class="page-heading"><div><div class="eyebrow">MY STUDY SPACE</div><h1>오늘도, 아는 만큼 확실하게.</h1><p>문제를 풀고, 헷갈렸던 개념만 다시 챙겨요.</p></div>${btn(icon('plus')+' 새 과목','new-course','white')}</section><div class="dashboard-grid"><div class="main-column"><section class="focus-card"><div class="focus-body"><span class="focus-label">오늘의 추천 학습</span><h2>${esc(c.name)}<br>짧게 풀고, 약점을 찾아요.</h2><p>검수된 ${real()?'학습':'샘플'} 문항 ${questionBank(state,c.id).length}개 · 객관식 + 단답형</p><div class="row wrap">${btn('퀴즈 시작하기','start','light',`data-course="${c.id}"`)}<span class="focus-note">${icon('clock',16)} 약 8분</span></div></div><div class="focus-score"><div class="score-ring" style="--value:${Math.round(c.mastery.reduce((a,b)=>a+b,0)/Math.max(1,c.mastery.length)*100)}"><div><strong>${Math.round(c.mastery.reduce((a,b)=>a+b,0)/Math.max(1,c.mastery.length)*100)}<small>%</small></strong><span>개념 숙련도</span></div></div><span>${real()?'나의 학습 현황':'샘플 학습 현황'}</span></div></section><section><div class="section-heading"><h2>내 과목 <span>${state.courses.length}</span></h2><span class="muted small">${real()?'나만의 학습 공간':'2026 가을학기 · 체험 데이터'}</span></div><div class="course-grid">${state.courses.map(courseTile).join('')}</div></section><section class="panel start-guide"><div class="guide-icon">${icon('link',28)}</div><div><h3>내 AI로 준비하고, CramMate에서 복습해요.</h3><p>교안부터 문항 제출까지 이어지는 연결 방법을 확인하세요.</p></div>${btn('AI 연결 안내','connect','ghost')}</section></div><aside class="right-column"><section class="panel stats-panel"><div class="section-heading"><h3>나의 학습 요약</h3><span class="badge">${real()?'내 기록':'체험'}</span></div><div class="stats"><div><strong>${count}<small>회</small></strong><span>완료한 퀴즈</span></div><div><strong>${weak}<small>개</small></strong><span>복습할 개념</span></div></div></section><section class="panel"><div class="section-heading"><h3>지금 챙길 개념</h3>${icon('target')}</div><p class="muted small">${esc(c.name)} · 숙련도가 낮은 순서</p>${weakList(c,3)}${btn('약점부터 복습','weak','outline full',`data-course="${c.id}"`)}</section><section class="note-card"><span class="note-kicker">STUDY NOTE</span><h3>틀린 문제는<br>다음 점수의 시작.</h3><p>정답을 외우기보다, 해설에서 놓친 개념 하나를 찾아보세요.</p><div class="note-lines"></div></section></aside></div>`;}
function coursePage(){const c=current(),bank=questionBank(state,c.id);return `<section class="page-heading"><div><div class="eyebrow">${esc(c.code)} · ${esc(c.exam)}</div><h1>${esc(c.name)}</h1><p>${esc(c.professor)} · 교안과 문제를 한곳에서</p></div>${btn('퀴즈 시작','start','primary',`data-course="${c.id}"`)}</section><div class="course-layout"><div>${real()?`<section class="panel ai-course"><div><span class="eyebrow">MAKE IT YOURS</span><h2>내 교안으로, 나만의 문제.</h2><p>교안 근거를 담은 8문제를 만들고 직접 검수해요.</p></div>${btn('AI 문제 만들기','generate','primary',c.materials.length?'':'disabled')}</section>`:''}<section class="panel"><div class="section-heading"><h2>내 교안</h2><span class="badge">${c.materials.length} / 20</span></div><label class="upload-box" for="pdf-input">${icon('upload',26)}<strong>교안 PDF 추가</strong><span>PDF · 1KB~50MB · 과목당 최대 20개</span><small>${real()?'개인 저장소에 보관하고 페이지별 텍스트를 추출해요. 스캔 PDF는 지원하지 않아요.':'로그인하면 실제 PDF 저장·분석을 사용할 수 있어요.'}</small><input type="file" id="pdf-input" accept="application/pdf,.pdf"></label><div class="file-list">${c.materials.map(f=>`<div class="file-row"><span class="file-icon">${icon('file')}</span><div><strong>${esc(f.name)}</strong><span>${f.sample?f.pages+'쪽 · 샘플 자료': real()?f.pages+'쪽 · 분석 완료':'선택한 파일 · 분석 전'}</span></div><span class="badge ${f.sample?'green':''}">${f.sample?'체험 자료':real()?'분석 완료':'추가됨'}</span></div>`).join('')}</div></section><section class="panel"><div class="section-heading"><h2>개념별 학습 현황</h2><span class="muted small">기준 숙련도 60%</span></div>${weakList(c)}</section></div><aside><section class="panel accent-panel"><span class="course-icon indigo">${icon('spark',24)}</span><h2>준비된 문제로<br>실력을 확인해요.</h2><p>승인된 ${bank.length}개 문항이 준비되어 있어요. 답을 제출하면 바로 해설을 볼 수 있어요.</p>${btn('퀴즈 시작','start','primary full',`data-course="${c.id}"`)}${btn('약점 복습','weak','outline full',`data-course="${c.id}"`)}</section><section class="panel"><div class="section-heading"><h3>과목 이용권</h3><span class="badge ${hasAccess(state,c)?'green':''}">${real()?'파일럿 무료':hasAccess(state,c)?'체험 이용 중':'미이용'}</span></div><p class="muted">${real()?'현재 파일럿 기간에는 무료로 퀴즈를 이용할 수 있어요.':hasAccess(state,c)?'이 과목의 샘플 퀴즈를 이용할 수 있어요.':'과목 이용권과 30일 구독을 모의 결제로 체험해 보세요.'}</p>${real()?'':btn(hasAccess(state,c)?'이용권 확인':'이용권 선택','pay','outline full',`data-course="${c.id}"`)}</section><section class="panel"><h3>내 AI 연결</h3><p class="muted">사용 중인 AI에서 교안의 개념과 문제를 준비하는 흐름이에요.</p>${btn('연결 안내 보기','connect','ghost full')}</section></aside></div>`;}
function quizPage(){if(!session)return dashboard();const q=session.questions[session.index],graded=session.graded,number=session.index+1;return `<section class="quiz-top"><div><span class="eyebrow">${esc(current().name)} · ${session.weak?'약점 복습':'확인 퀴즈'}</span><h1>한 문제씩, 확실하게.</h1></div>${btn('퀴즈 나가기','quit','ghost')}</section><div class="quiz-layout"><section class="panel question-panel"><div class="row between"><span class="badge indigo">${q.type==='choice'?'객관식':'단답형'}</span><span class="muted">${number} / ${session.questions.length}</span></div><div class="quiz-progress"><i style="width:${number/session.questions.length*100}%"></i></div><p class="eyebrow">${esc(topicsFor(state.courses.find(c=>c.id===q.course))[q.topic])}</p><h2>${esc(q.prompt)}</h2><fieldset class="answer-options" ${graded?'disabled':''}><legend class="sr-only">답안 선택</legend>${q.type==='choice'?q.options.map((o,i)=>`<label class="answer-option ${session.answer===i?'selected':''} ${graded&&q.correct===i?'is-correct':''} ${graded&&session.answer===i&&!session.correct?'is-wrong':''}"><input type="radio" name="answer" value="${i}" ${session.answer===i?'checked':''}><span class="option-number">${i+1}</span><span>${esc(o)}</span>${graded&&q.correct===i?icon('check'):''}</label>`).join(''):`<label class="field-label" for="short-answer">답을 입력해 주세요</label><input id="short-answer" class="text-input" value="${esc(session.answer??'')}" autocomplete="off" placeholder="짧은 용어로 답해 주세요"><p class="muted small">등록된 정답·동의어와 일치하는지 확인해요. 다른 표현은 정답으로 인정되지 않을 수 있어요.</p>`}</fieldset>${graded?`<div class="feedback ${session.correct?'correct':'wrong'}" role="status"><strong>${session.correct?'정답이에요. 잘 이해하고 있네요!':'괜찮아요. 이 개념을 같이 확인해요.'}</strong><p><b>정답:</b> ${esc(q.type==='choice'?q.options[q.correct]:q.model)}</p><p>${esc(q.explanation)}</p></div>`:''}<div class="quiz-footer"><span class="muted small">${esc(q.source)}</span>${graded?btn(number===session.questions.length?'결과 확인':'다음 문제','next'):btn('답안 제출','submit-answer')}</div></section><aside class="panel quiz-aside"><h3>학습 진행</h3><div class="question-dots">${session.questions.map((_,i)=>`<span class="${i<session.responses.length?(session.responses[i].correct?'done':'missed'):i===session.index?'current':''}">${i+1}</span>`).join('')}</div><div class="divider"></div><p>모르는 문제는 빈 답안으로 제출해도 괜찮아요.</p><p class="muted small">결과에서 다시 볼 개념을 모아드릴게요.</p></aside></div>`;}
function resultPage(){const r=lastResult;if(!r)return historyPage();const c=state.courses.find(c=>c.id===r.courseId);return `<section class="page-heading"><div><div class="eyebrow">QUIZ COMPLETE</div><h1>한 걸음 더 이해했어요.</h1><p>${esc(c.name)} · ${r.responses.length}문항 학습 완료</p></div>${btn('학습 홈','dashboard','white')}</section><div class="result-summary"><div class="result-score"><span>이번 퀴즈 점수</span><strong>${r.score}<small>점</small></strong><p>${r.responses.filter(x=>x.correct).length} / ${r.responses.length} 정답</p></div><div class="result-message"><h2>${r.score>=80?'좋은 흐름이에요.':'이제, 어디를 복습할지 보여요.'}</h2><p>오답 개념은 10분 뒤, 정답 개념은 하루 뒤 다시 확인해요.</p><span class="muted small">이번 학습 퀴즈의 점수예요. 실제 시험 등수·학점 예측은 비교 데이터가 쌓인 뒤 제공할 예정이에요.</span></div></div><div class="course-layout"><section class="panel"><div class="section-heading"><h2>개념 숙련도 변화</h2><span class="badge">이번 응시 반영</span></div>${topicsFor(c).map((t,i)=>`<div class="mastery-row"><strong>${esc(t)}</strong><span>${Math.round(r.before[i]*100)}% <span class="muted">→</span> <b class="${r.after[i]>=r.before[i]?'positive':'negative'}">${Math.round(r.after[i]*100)}%</b></span></div>`).join('')}<div class="divider"></div><h3>문항별 해설</h3>${r.responses.map((a,i)=>{const q=(r.questions||state.questions).find(q=>q.id===a.questionId);return `<details class="answer-detail"><summary><span class="answer-badge ${a.correct?'ok':'bad'}">${a.correct?'정답':'복습'}</span><span>${i+1}. ${esc(q.prompt)}</span></summary><p><b>정답:</b> ${esc(q.type==='choice'?q.options[q.correct]:q.model)}</p><p>${esc(q.explanation)}</p></details>`;}).join('')}</section><aside class="panel fit"><h2>지금 한 번 더</h2><p class="muted">숙련도가 낮은 개념부터 5문제를 풀어보세요.</p>${btn('약점 복습 시작','weak','primary full',`data-course="${c.id}"`)}${btn('과목으로 돌아가기','course','outline full',`data-course="${c.id}"`)}</aside></div>`;}
function reviewPage(){return `<section class="page-heading"><div><div class="eyebrow">REVIEW</div><h1>헷갈렸던 개념부터.</h1><p>숙련도 60% 미만의 개념을 먼저 확인해요.</p></div></section><div class="course-grid">${state.courses.map(c=>`<section class="panel"><div class="section-heading"><h2>${esc(c.name)}</h2><span class="badge orange">복습 ${c.mastery.filter(x=>x<.6).length}개</span></div>${weakList(c)}${btn('약점 복습','weak','primary full',`data-course="${c.id}"`)}<p class="muted small">${Object.keys(state.reviewDue).some(k=>k.startsWith(c.id+':'))?'응시 결과에 따라 다음 복습 시각이 갱신되었어요.':real()?'아직 응시 전이에요. 퀴즈를 풀면 숙련도가 갱신돼요.':'아직 응시 전이에요. 샘플 숙련도를 보여드려요.'}</p></section>`).join('')}</div>`;}
function historyPage(){return `<section class="page-heading"><div><div class="eyebrow">HISTORY</div><h1>쌓이는 나의 학습 기록.</h1><p>${real()?'로그인한 계정에 저장된 학습 기록을 확인하세요.':'이 브라우저에 저장된 체험 기록을 확인하세요.'}</p></div></section>${state.history.length?`<section class="panel"><div class="history-list">${state.history.map(r=>`<button class="history-row" data-action="result" data-id="${r.id}"><span class="course-icon indigo">${icon('check')}</span><span><strong>${esc(state.courses.find(c=>c.id===r.courseId).name)}</strong><small>${new Date(r.at).toLocaleString('ko-KR')} · ${r.responses.length}문항</small></span><b>${r.score}<small>점</small></b><span class="muted small">해설 보기</span></button>`).join('')}</div></section>`:`<section class="panel empty-state">${icon('book',38)}<h2>첫 퀴즈를 기다리고 있어요.</h2><p>문제를 풀면 점수와 개념별 학습 기록이 여기에 쌓여요.</p>${btn('첫 퀴즈 시작','start','primary','data-course="os"')}</section>`}`;}
function connectPage(){return integrationPage();}
function adminPage(){const pending=state.questions.filter(q=>q.status==='pending');return `<section class="page-heading"><div><div class="eyebrow">QUESTION REVIEW</div><h1>좋은 문제를 함께 쌓아요.</h1><p>내 문항 검수 · 승인한 문항만 나의 퀴즈에 포함돼요.</p></div><span class="badge orange">검수 대기 ${pending.length}건</span></section><div class="notice">${real()?'교안 근거와 정답을 확인한 뒤 승인해 주세요. AI가 만든 문제에는 오류가 있을 수 있어요.':'샘플 문항의 승인·반려 흐름을 체험하는 화면이에요.'}</div>${pending.length?pending.map(q=>`<article class="panel review-card"><div class="row between"><span class="badge">${esc(state.courses.find(c=>c.id===q.course).name)} · ${esc(topicsFor(state.courses.find(c=>c.id===q.course))[q.topic])}</span><span class="muted small">${q.type==='choice'?'객관식':'단답형'}</span></div><h2>${esc(q.prompt)}</h2><ol class="review-options">${q.options?.map((o,i)=>`<li class="${i===q.correct?'positive':''}">${esc(o)} ${i===q.correct?'(정답)':''}</li>`).join('')||esc(q.model)}</ol><p class="muted small">근거: ${esc(q.source)}</p><p class="muted">${esc(q.explanation)}</p><div class="row end">${btn('반려','reject','ghost',`data-id="${q.id}"`)}${btn('승인','approve','primary',`data-id="${q.id}"`)}</div></article>`).join(''):`<section class="panel empty-state">${icon('check',38)}<h2>대기 중인 문항이 없어요.</h2><p>${real()?'과목에 교안을 추가하고 AI 문제를 만들어 보세요.':'샘플 제출로 검수 흐름을 다시 체험할 수 있어요.'}</p>${real()?btn('내 과목으로','dashboard','outline'):btn('샘플 문항 제출','sample-submit','outline')}</section>`}<section class="panel"><div class="section-heading"><h2>승인된 문제은행</h2><span class="muted">${state.questions.filter(q=>q.status==='approved').length}문항</span></div>${state.questions.filter(q=>q.status==='approved').map(q=>`<div class="bank-row"><div><span class="muted small">${esc(state.courses.find(c=>c.id===q.course).name)}</span><p>${esc(q.prompt)}</p></div>${btn('삭제','delete-question','ghost danger',`data-id="${q.id}"`)}</div>`).join('')}</section>`;}
function render(){if(!real())saveDemo(state);const titles={dashboard:'나의 학습',course:current()?.name||'새 과목',quiz:'퀴즈 풀이',result:'학습 결과',history:'학습 기록',review:'약점 복습',connect:'AI 연결',admin:'문항 검수'};document.title=`CramMate · ${titles[active]}`;const n=state.questions.filter(q=>q.status==='pending').length;const navigation=[['dashboard','grid','나의 학습'],['review','target','약점 복습'],['history','clock','학습 기록'],['connect','link','AI 연결']];app.innerHTML=`<div class="layout"><aside class="sidebar ${menuOpen?'open':''}"><a class="brand" href="#" data-action="dashboard"><span class="brand-mark">C</span><span>CramMate<small>벼락치기 구조대</small></span></a><div class="workspace-label">STUDY WORKSPACE</div><nav aria-label="주요 메뉴">${navigation.map(([id,ico,label])=>`<button class="nav-item ${active===id?'active':''}" data-action="${id}" ${active===id?'aria-current="page"':''}>${icon(ico)}<span>${label}</span></button>`).join('')}</nav><div class="sidebar-divider"></div><div class="workspace-label">MY COURSES</div><nav aria-label="내 과목">${state.courses.map(c=>`<button class="nav-item ${active==='course'&&c.id===selectedCourse?'active':''}" data-action="course" data-course="${c.id}"><span class="mini-course ${c.color}">${esc(c.name[0])}</span><span>${esc(c.name)}</span></button>`).join('')}</nav><div class="sidebar-bottom"><button class="nav-item ${active==='admin'?'active':''}" data-action="admin">${icon('shield')}<span>문항 검수</span><span class="nav-count">${n}</span></button><div class="user-box"><span class="avatar">S</span><span><strong>${real()?esc(connection.user.email):'학생 체험 계정'}</strong><small>${real()?'나의 학습 공간':'AltTab · 서비스 체험'}</small></span></div></div></aside><div class="workspace"><header class="topbar"><div class="row"><button class="mobile-menu" data-action="menu" aria-label="메뉴 열기" aria-expanded="${menuOpen}">${icon('menu')}</button><span class="breadcrumb">학습 공간 <span>/</span> <strong>${esc(titles[active])}</strong></span></div><div class="row"><span class="demo-tag">${real()?'파일럿':'체험 버전'}</span>${btn(real()?'내 계정':'로그인','account','ghost')}</div></header><div class="demo-bar"><span>${real()?'나의 교안으로 준비하는 CramMate':'샘플 데이터로 둘러보는 CramMate'}</span><span>${connection.error?esc(connection.error):real()?'학습 기록이 내 계정에 저장돼요.':'체험 기록은 이 브라우저에 저장돼요.'}</span></div><main id="main" tabindex="-1">${({dashboard,course:coursePage,quiz:quizPage,result:resultPage,review:reviewPage,history:historyPage,connect:connectPage,admin:adminPage}[active]||dashboard)()}</main><footer>© 2026 CramMate <span>AltTab · Student-first learning</span></footer></div></div>`;}
function start(courseId,weak=false){selectedCourse=courseId;try{const questions=selectQuiz(state,courseId,weak);session={questions,index:0,answer:null,responses:[],graded:false,weak,started:Date.now()};nav('quiz');}catch(e){if(!hasAccess(state,current()))payDialog(courseId);else toast(e.message);}}
function payDialog(id){selectedCourse=id;const c=current();if(hasAccess(state,c)){toast('이미 이용권이 있어요. 현재 세션에서 이용할 수 있어요.');return;}dialog(`<span class="eyebrow">STUDY PASS</span><h2>나에게 맞는 이용권</h2><p class="muted">실제 청구 없는 모의 결제예요.</p><form id="payment-form"><label class="plan-option"><input type="radio" name="plan" value="course"><span><strong>과목 이용권</strong><small>${esc(c.name)} · 이번 과목만</small></span><b>2,900원</b></label><label class="plan-option"><input type="radio" name="plan" value="subscription"><span><strong>시험 기간 구독</strong><small>30일 · 모든 과목</small></span><b>가격 미정</b></label><p id="payment-error" class="form-error" role="alert"></p><button class="btn primary full" id="pay-submit" type="submit" disabled>모의 결제 완료</button><button type="button" class="btn ghost full" data-action="pay-fail">실패 상황 체험</button></form>`);}
function newCourse(){dialog(`<span class="eyebrow">NEW COURSE</span><h2>새 과목 만들기</h2><p class="muted">${real()?'내 계정에 과목을 추가해요.':'체험 공간에 과목을 추가해요.'}</p><form id="course-form"><label class="field-label" for="course-name">과목명</label><input id="course-name" name="name" class="text-input" maxlength="40" required placeholder="예: 컴퓨터 네트워크"><label class="field-label" for="professor-name">담당 교수</label><input id="professor-name" name="professor" class="text-input" maxlength="30" placeholder="선택 입력"><label class="field-label" for="exam-name">준비할 시험</label><select id="exam-name" name="exam" class="text-input"><option>중간고사</option><option>기말고사</option></select><button class="btn primary full" type="submit">과목 만들기</button></form>`);}
document.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el)return;e.preventDefault();const action=el.dataset.action,id=el.dataset.course;try{
 if(['dashboard','history','review','connect','admin'].includes(action)){if(session&&active==='quiz'){dialog(`<h2>퀴즈를 나갈까요?</h2><p>진행 중인 답안은 완료 기록에 남지 않아요.</p>${btn('계속 풀기','close-dialog','outline')}${btn('나가기','confirm-quit')}`);return;}nav(action);}
 else if(action==='course'){if(active==='quiz'){dialog(`<h2>퀴즈를 나갈까요?</h2><p>진행 중인 답안은 완료 기록에 남지 않아요.</p>${btn('계속 풀기','close-dialog','outline')}${btn('나가기','confirm-quit')}`);return;}selectedCourse=id;nav('course');}
 else if(action==='start'||action==='weak')start(id,action==='weak');
 else if(action==='new-course')newCourse();
 else if(action==='account')accountDialog();
 else if(action==='signout'){await signOut();modal.close();}
 else if(action==='reload'){await reloadState();render();}
 else if(action==='generate')generateDialog();
 else if(action==='confirm-generate'){await withBusy(el,async()=>{const result=await api('generate',{courseId:selectedCourse});await reloadState();modal.close();nav('admin');toast(result.count+'개 문항을 만들었어요. 근거와 정답을 검수해 주세요.');});}
 else if(action==='create-token'){await withBusy(el,createToken);}
 else if(action==='tokens')await tokenList();
 else if(action==='revoke-token'){await api('revoke-token',{id:el.dataset.id});await tokenList();}
 else if(action==='copy-token'){await navigator.clipboard.writeText(document.querySelector('#token-value').value);toast('복사했어요. 안전한 곳에 보관해 주세요.');}
 else if(action==='reset-demo'){state=resetDemo();session=null;lastResult=null;selectedCourse='os';modal.close();nav('dashboard');}
 else if(action==='pay')payDialog(id);
 else if(action==='close-dialog')modal.close();
 else if(action==='menu'){menuOpen=!menuOpen;render();}
 else if(action==='about')accountDialog();
 else if(action==='submit-answer'){if(!session||session.graded)return;const q=session.questions[session.index];if(q.type==='short')session.answer=document.querySelector('#short-answer').value;session.correct=scoreAnswer(q,session.answer);session.responses.push({questionId:q.id,answer:session.answer,correct:session.correct});session.graded=true;render();}
 else if(action==='next'){if(!session?.graded)return;if(session.index+1===session.questions.length){if(real()){await withBusy(el,async()=>{session.requestId ||= crypto.randomUUID();lastResult=await api('attempt',{courseId:selectedCourse,requestId:session.requestId,responses:session.responses.map(({questionId,answer})=>({questionId,answer}))});await reloadState();session=null;nav('result');});}else{lastResult=applyResult(state,selectedCourse,session.responses);session=null;nav('result');}}else{session.index++;session.answer=null;session.graded=false;render();window.scrollTo({top:0,behavior:'instant'});}}
 else if(action==='quit')dialog(`<h2>퀴즈를 나갈까요?</h2><p>진행 중인 답안은 완료 기록에 남지 않아요.</p><div class="row end">${btn('계속 풀기','close-dialog','outline')}${btn('나가기','confirm-quit')}</div>`);
 else if(action==='confirm-quit'){session=null;modal.close();nav('dashboard');}
 else if(action==='result'){lastResult=state.history.find(r=>r.id===el.dataset.id);selectedCourse=lastResult.courseId;nav('result');}
 else if(action==='approve'||action==='reject'){if(real()){await api('review',{id:el.dataset.id,status:action==='approve'?'approved':'rejected'});await reloadState();}else reviewQuestion(state,el.dataset.id,action==='approve'?'approved':'rejected');render();toast(action==='approve'?'문제은행에 추가했어요.':'문항을 반려했어요.');}
 else if(action==='delete-question')dialog(`<h2>문제은행에서 삭제할까요?</h2><p>다음 퀴즈부터 출제되지 않아요. 기존 응시 해설은 유지돼요.</p><div class="row end">${btn('취소','close-dialog','outline')}${btn('삭제','confirm-delete','primary',`data-id="${el.dataset.id}"`)}</div>`);
 else if(action==='confirm-delete'){if(real()){await api('review',{id:el.dataset.id,status:'deleted'});await reloadState();}else reviewQuestion(state,el.dataset.id,'deleted');modal.close();render();toast('문제은행에서 삭제했어요.');}
 else if(action==='sample-submit'){if(real()){toast('과목 화면에서 실제 문제를 생성해 주세요.');return;}const exists=state.questions.some(q=>q.id==='sample-new'&&q.status!=='rejected');if(exists){toast('이미 제출한 샘플 문항이에요. 검수 화면에서 확인해 주세요.');return;}state.questions=state.questions.filter(q=>q.id!=='sample-new');state.questions.push({id:'sample-new',course:'os',topic:0,type:'choice',status:'pending',prompt:'프로세스의 실행 상태와 레지스터 등 관리 정보를 저장하는 자료구조는?',options:['PCB','TLB','페이지 프레임','디렉터리'],correct:0,explanation:'PCB(Process Control Block)는 운영체제가 프로세스를 관리하는 데 필요한 정보를 담습니다.',source:'체험용 자체 작성 문항'});toast('검수 대기에 샘플 문항 1개를 추가했어요.');nav('admin');}
 else if(action==='pay-fail'){document.querySelector('#payment-error').textContent='모의 결제에 실패했어요. 이용권은 추가되지 않았어요.';}
 else if(action==='copy-prompt'){const text='운영체제 교안에서 중요한 개념을 뽑고, 근거 페이지와 해설이 있는 문제 10개를 만들어 검수 대기로 제출해줘.';try{await navigator.clipboard.writeText(text);toast('요청문을 복사했어요.');}catch{toast('복사할 수 없어요. 표시된 요청문을 직접 선택해 주세요.');}}
 }catch(err){toast(err.message);}});
document.addEventListener('change',e=>{if(e.target.name==='answer'&&session&&!session.graded){session.answer=Number(e.target.value);document.querySelectorAll('.answer-option').forEach(label=>label.classList.toggle('selected',label.querySelector('input').checked));}if(e.target.name==='plan'){document.querySelector('#pay-submit').disabled=false;document.querySelector('#payment-error').textContent='';}});
render();
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();const tools=[{name:'crammate_get_demo_state',title:'학습 상태 조회',description:'현재 체험 세션의 과목, 완료한 퀴즈 수, 검수 대기 수를 조회합니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({courses:state.courses.map(c=>({id:c.id,name:c.name,approvedQuestions:questionBank(state,c.id).length})),completedQuizzes:state.history.length,pendingQuestions:state.questions.filter(q=>q.status==='pending').length})},{name:'crammate_open_course',title:'과목 화면 열기',description:'체험 과목의 학습 화면을 엽니다. 퀴즈를 시작하거나 제출하지 않습니다.',inputSchema:{type:'object',properties:{courseId:{type:'string'}},required:['courseId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||typeof input.courseId!=='string'||!state.courses.some(c=>c.id===input.courseId))throw Error('유효한 과목 ID가 필요합니다.');if(active==='quiz')throw Error('진행 중인 퀴즈를 먼저 완료하거나 종료해 주세요.');selectedCourse=input.courseId;nav('course');return {opened:true,courseId:selectedCourse};}}];for(const t of tools){try{Promise.resolve(context.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}

function emptyDashboard(){return `<section class="page-heading"><div><div class="eyebrow">YOUR FIRST STEP</div><h1>이번 시험, 같이 준비해요.</h1><p>첫 과목을 만들고 교안을 올리면 나만의 학습 공간이 시작돼요.</p></div></section><section class="focus-card welcome-card"><div><span class="focus-label">나의 첫 학습 공간</span><h2>교안 한 권에서<br>확실한 이해까지.</h2><p>과목 만들기 → PDF 추가 → 문제 생성·검수 → 퀴즈</p>${btn('첫 과목 만들기','new-course','light')}</div><div class="welcome-symbol">${icon('book',100)}</div></section>${connection.error?`<section class="panel"><h3>저장소 연결을 확인해 주세요.</h3><p>${esc(connection.error)}</p>${btn('다시 연결','reload','outline')}</section>`:''}`;}
function integrationPage(){const cfg=connection.config;return `<section class="page-heading"><div><div class="eyebrow">CONNECTED LEARNING</div><h1>어떤 AI를 쓰든, 한곳에 쌓이도록.</h1><p>웹에서 문제를 만들거나, 내 AI와 개인 학습 공간을 연결하세요.</p></div></section><div class="course-layout"><div><section class="panel"><span class="eyebrow">01 · WEB AI</span><h2>교안으로 바로 문제 만들기</h2><p>과목에 PDF를 올린 뒤 ‘AI 문제 만들기’를 누르세요. 생성한 문항은 내 검수함으로 들어오고, 승인하면 퀴즈에서 풀 수 있어요.</p><div class="connection-row"><span>로그인·저장소 설정</span><span class="badge ${cfg.authReady?'green':''}">${cfg.authReady?'설정 확인':'설정 필요'}</span></div><div class="connection-row"><span>서버 AI 설정</span><span class="badge ${cfg.aiReady?'green':''}">${cfg.aiReady?'설정 확인':'설정 필요'}</span></div><p class="muted small">설정 확인은 키가 등록되어 있다는 뜻이에요. 실제 연결 결과는 로그인·생성 시 확인할 수 있어요.</p>${btn(real()?'내 과목으로':'로그인하고 시작','account-or-home','primary')}</section><section class="panel"><span class="eyebrow">02 · MY AI, MY WORKSPACE</span><h2>내 AI와 MCP로 연결</h2><p>HTTP MCP와 인증 헤더를 지원하는 클라이언트에서 사용할 수 있어요. 학생마다 토큰을 따로 발급하고, 본인 자료와 학습 기록만 조회합니다.</p><label class="field-label" for="mcp-endpoint">MCP 서버 주소</label><input id="mcp-endpoint" class="text-input mono" readonly value="${esc(location.origin)}/api/mcp"><div class="row wrap token-actions">${btn('개인 연결 토큰 만들기','create-token','primary',real()&&cfg.mcpReady?'':'disabled')}${btn('발급한 토큰 관리','tokens','outline',real()?'':'disabled')}</div><p class="muted small">토큰은 30일간 유효해요. 토큰을 받은 AI는 교안·학습 기록을 읽고 검수 대기 문항을 제출할 수 있어요. 다른 사람에게 공유하지 마세요.</p>${!cfg.mcpReady?'<div class="notice">MCP 서버 연결 설정이 아직 필요해요. 연결이 준비되면 토큰을 발급할 수 있어요.</div>':''}<div class="prompt-box"><strong>이렇게 부탁해 보세요</strong><p>내 과목 목록을 확인하고, 운영체제 교안의 근거 페이지를 붙여 8문제를 만들어 검수 대기로 제출해 줘.</p></div></section></div><aside class="panel fit"><h3>팀원이 다른 AI를 써도 괜찮아요.</h3><p>모두 같은 GitHub의 문서와 API 규격을 기준으로 개발하면 돼요.</p><ul class="plain-list"><li>화면·백엔드 코드는 AltTab2에서 관리</li><li>DB 구조와 MCP 계약을 문서로 공유</li><li>각자의 개인 토큰과 자료는 분리</li><li>생성한 문제는 사람이 검수</li></ul><a class="btn outline full" href="https://github.com/Snow0821/AltTab2" target="_blank" rel="noopener noreferrer">GitHub 열기</a></aside></div>`;}
function accountDialog(){
  if(real()){dialog(`<span class="eyebrow">MY ACCOUNT</span><h2>나의 학습 계정</h2><p>${esc(connection.user.email)}</p><p class="muted">학습 기록은 이 계정에 저장됩니다. 현재 파일럿은 무료예요.</p>${btn('로그아웃','signout','outline full')}`);return;}
  dialog(`<span class="eyebrow">WELCOME TO CRAMMATE</span><h2>나의 학습을 이어가세요.</h2><p class="muted">로그인하면 내 교안과 응시 기록을 저장할 수 있어요. 샘플 기록은 개인 계정에 옮겨지지 않아요.</p>${connection.config.authReady?`<form id="auth-form"><label class="field-label" for="auth-email">이메일</label><input id="auth-email" name="email" class="text-input" type="email" autocomplete="email" required><label class="field-label" for="auth-password">비밀번호</label><input id="auth-password" name="password" class="text-input" type="password" minlength="8" autocomplete="current-password" required><p id="auth-error" class="form-error" role="alert"></p><button name="mode" value="login" class="btn primary full" type="submit">로그인</button><button name="mode" value="signup" class="btn outline full" type="submit">새 계정 만들기</button><p class="muted small">가입 후 이메일 인증이 필요할 수 있어요.</p></form>`:'<div class="notice">로그인 서버 연결을 준비 중이에요. 지금은 샘플 퀴즈와 복습 흐름을 체험할 수 있어요.</div>'}<div class="divider"></div>${btn('체험 기록 초기화','reset-demo','ghost full')}`);
}
function generateDialog(){dialog(`<span class="eyebrow">AI QUESTION BUILDER</span><h2>교안으로 8문제를 만들까요?</h2><p>${esc(current().name)} 교안의 텍스트를 연결된 AI 제공자에게 보내 문제와 해설을 만들어요. 긴 교안은 앞부분부터 분석합니다.</p><div class="notice">AI가 만든 내용에는 오류가 있을 수 있어요. 근거 페이지를 확인하고 직접 승인해야 퀴즈에 포함됩니다.</div><p class="muted small">한 번 생성하는 데 최대 1분 정도 걸려요. 1분에 한 번, 하루 20회까지 사용할 수 있어요.</p><div class="row end">${btn('취소','close-dialog','outline')}${btn('교안을 보내고 생성','confirm-generate','primary',connection.config.aiReady?'':'disabled')}</div>${connection.config.aiReady?'':'<p class="form-error">서버 AI 연결 설정이 필요해요. MCP를 연결해 내 AI로 제출할 수도 있어요.</p>'}`);}
async function withBusy(element,fn){if(busy)return;busy=true;const label=element?.textContent;if(element){element.disabled=true;element.textContent='처리 중…';}try{return await fn();}finally{busy=false;if(element?.isConnected){element.disabled=false;element.textContent=label;}}}
async function reloadState(){const loaded=await api('load');state=loaded;connection.error=null;if(!state.courses.some(c=>c.id===selectedCourse))selectedCourse=state.courses[0]?.id;}
async function createToken(){const r=await api('create-token',{name:'내 AI'});const config={mcpServers:{crammate:{url:location.origin+'/api/mcp',headers:{Authorization:'Bearer '+r.token}}}};dialog(`<span class="eyebrow">PERSONAL CONNECTION</span><h2>토큰을 안전하게 보관하세요.</h2><p>이 화면을 닫으면 원문을 다시 볼 수 없어요. 만료: ${new Date(r.expires_at).toLocaleDateString('ko-KR')}</p><label class="field-label" for="token-value">내 연결 토큰</label><input class="text-input mono" id="token-value" readonly value="${esc(r.token)}">${btn('토큰 복사','copy-token','outline full')}<label class="field-label" for="mcp-config">HTTP MCP 설정 예시</label><textarea class="text-input mono" id="mcp-config" readonly rows="12">${esc(JSON.stringify(config,null,2))}</textarea><p class="muted small">클라이언트마다 설정 형식이 다를 수 있어요. 이 토큰으로 다른 사람의 자료에 접근할 수는 없어요.</p>`);}
async function tokenList(){const tokens=await api('tokens');dialog(`<h2>내 연결 토큰</h2><p class="muted">쓰지 않는 연결은 즉시 폐기할 수 있어요.</p>${tokens.length?tokens.map(t=>`<div class="token-row"><div><strong>${esc(t.name)}</strong><p class="small muted">${new Date(t.expires_at).toLocaleDateString('ko-KR')} 만료 · ${t.revoked_at?'폐기됨':Date.parse(t.expires_at)<Date.now()?'만료됨':'활성'}</p></div>${!t.revoked_at?btn('폐기','revoke-token','ghost danger',`data-id="${esc(t.id)}"`):''}</div>`).join(''):'<p>발급한 토큰이 없어요.</p>'}`);}
document.addEventListener('click',e=>{if(e.target.closest('[data-action="account-or-home"]')){if(real())nav('dashboard');else accountDialog();}});
document.addEventListener('submit',async e=>{
  if(!['auth-form','course-form','payment-form'].includes(e.target.id))return;e.preventDefault();
  const form=e.target,data=new FormData(form),button=e.submitter;
  try{await withBusy(button,async()=>{
    if(form.id==='auth-form'){
      const r=await authenticate(data.get('email').trim(),data.get('password'),button?.value==='signup');
      if(r.verificationRequired){document.querySelector('#auth-error').textContent='이메일로 보낸 인증 링크를 확인한 뒤 로그인해 주세요.';}else{modal.close();toast('나의 학습 공간을 불러오고 있어요.');}
    }else if(form.id==='course-form'){
      const input={name:data.get('name').trim(),professor:data.get('professor').trim(),exam:data.get('exam')};if(!input.name)return;
      if(real()){const c=await api('create-course',input);await reloadState();selectedCourse=c.id;}
      else{const c={...input,id:'course-'+crypto.randomUUID(),professor:input.professor||'교수 미입력',code:'NEW',color:'indigo',entitled:false,materials:[],mastery:[],topics:[]};state.courses.push(c);selectedCourse=c.id;}
      modal.close();nav('course');toast('과목을 만들었어요. 교안을 추가해 보세요.');
    }else{purchase(state,selectedCourse,data.get('plan'));modal.close();render();toast('모의 결제가 완료됐어요. 실제 청구는 없어요.');}
  });}catch(error){const field=form.querySelector('.form-error');if(field)field.textContent=error.message;else toast(error.message);}
});
document.addEventListener('change',async e=>{
  if(e.target.id!=='pdf-input')return;const file=e.target.files[0];if(!file)return;const c=current(),input=e.target;
  try{await withBusy(input,async()=>{
    if(!/\.pdf$/i.test(file.name))throw Error('PDF 파일만 올릴 수 있어요.');
    if(file.size<1024||file.size>50*1024*1024)throw Error('1KB~50MB PDF를 선택해 주세요.');
    if(c.materials.length>=20)throw Error('교안은 과목당 최대 20개까지 추가할 수 있어요.');
    if(await file.slice(0,5).text()!=='%PDF-')throw Error('유효한 PDF 파일을 선택해 주세요.');
    const bytes=await file.arrayBuffer(),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).map(x=>x.toString(16).padStart(2,'0')).join('');
    if(c.materials.some(f=>f.hash===hash))throw Error('이미 추가한 교안이에요.');
    if(real()){toast('PDF를 저장하고 분석하고 있어요…');await uploadPDF(c.id,file);await reloadState();toast('교안을 저장하고 분석했어요. 이제 AI 문제를 만들 수 있어요.');}
    else{c.materials.push({name:file.name,hash,sample:false});toast('체험 목록에 추가했어요. 실제 저장·분석은 로그인 후 사용할 수 있어요.');}
    render();
  });}catch(error){toast(error.message);input.value='';}
});
initialize(async()=>{
  session=null;lastResult=null;active='dashboard';
  if(real()){state=emptyState();try{await reloadState();}catch(error){connection.error=error.message;}}
  else{state=demoState();selectedCourse=state.courses[0]?.id;}
  render();
});
