export const topics = ['프로세스와 스레드','CPU 스케줄링','동기화','메모리 관리','교착 상태'];
const q = (id,course,topic,prompt,options,correct,explanation) => ({id,course,topic,prompt,options,correct,explanation,type:'choice',status:'approved',source:'체험용 자체 작성 문항'});
export function initialState(){return {
 courses:[{id:'os',name:'운영체제',professor:'김교수',exam:'중간고사',code:'CS301',color:'indigo',entitled:true,materials:[{name:'운영체제_중간고사_핵심노트.pdf',pages:42,sample:true}],mastery:[.55,.35,.4,.7,.3]}, {id:'db',name:'데이터베이스',professor:'이교수',exam:'중간고사',code:'CS204',color:'teal',entitled:false,materials:[{name:'관계형_데이터베이스_요약.pdf',pages:28,sample:true}],mastery:[.3,.4,.5,.3,.5]}],
 questions:[q('os-1','os',0,'같은 프로세스에 속한 스레드들이 일반적으로 공유하는 것은?', ['코드 영역과 힙','각 스레드의 스택','프로그램 카운터','CPU 레지스터'],0,'스레드는 프로세스의 코드, 데이터, 힙을 공유합니다. 스택과 레지스터 상태는 스레드마다 독립적으로 유지합니다.'),
 q('os-2','os',1,'라운드 로빈 스케줄링의 타임 퀀텀을 매우 크게 설정하면 어떤 방식에 가까워질까요?', ['최단 작업 우선(SJF)','선입선출(FCFS)','최단 잔여 시간 우선(SRTF)','우선순위 스케줄링'],1,'타임 퀀텀이 충분히 길면 실행 중인 프로세스가 대부분 완료될 때까지 CPU를 사용하므로 FCFS에 가까워집니다.'),
 q('os-3','os',2,'여러 스레드가 공유 변수에 동시에 접근할 때, 임계 구역을 한 번에 하나의 스레드만 실행하게 하는 조건은?', ['상호 배제','페이징','선점','문맥 교환'],0,'상호 배제(mutual exclusion)는 동시에 둘 이상의 스레드가 임계 구역에 들어가지 못하게 하는 조건입니다.'),
 q('os-4','os',3,'페이지 테이블이 연결하는 두 정보는 무엇일까요?', ['파일 이름과 확장자','프로세스 ID와 우선순위','가상 페이지 번호와 물리 프레임 번호','스레드 ID와 스택 크기'],2,'페이지 테이블은 가상 주소의 페이지 번호를 물리 메모리 프레임 번호에 연결합니다.'),
 q('os-5','os',4,'다음 중 교착 상태의 네 가지 필요조건에 포함되지 않는 것은?', ['상호 배제','점유와 대기','순환 대기','선점 가능'],3,'네 가지 조건은 상호 배제, 점유와 대기, 비선점, 순환 대기입니다. 선점 가능은 비선점과 반대입니다.'),
 {id:'os-6',course:'os',topic:1,type:'short',status:'approved',prompt:'실행 중인 프로세스의 상태를 저장하고 다른 프로세스의 상태를 복원해 CPU 실행을 넘기는 작업을 무엇이라고 하나요?',accepted:['문맥교환','컨텍스트스위칭','contextswitch','contextswitching'],model:'문맥 교환 (context switching)',explanation:'문맥 교환은 기존 프로세스의 레지스터 등 실행 상태를 저장하고 다음 프로세스의 상태를 복원하는 작업입니다.',source:'체험용 자체 작성 문항'},
 q('db-1','db',0,'관계형 데이터베이스에서 한 행을 유일하게 식별하는 키는?', ['외래키','기본키','후보 행','인덱스 이름'],1,'기본키는 각 행을 고유하게 식별하며 NULL을 허용하지 않습니다.'),
 q('db-2','db',1,'두 테이블의 관련된 행을 연결하는 연산은?', ['JOIN','DROP','COMMIT','GRANT'],0,'JOIN은 관련 열을 기준으로 두 테이블의 행을 결합합니다.'),
 q('db-3','db',2,'트랜잭션의 작업이 모두 수행되거나 전혀 수행되지 않아야 한다는 성질은?', ['고립성','지속성','원자성','중복성'],2,'원자성은 트랜잭션 전체가 하나의 단위로 완료되거나 취소되어야 함을 뜻합니다.'),
 q('db-4','db',3,'데이터 중복과 갱신 이상을 줄이기 위해 테이블을 구조화하는 과정은?', ['정규화','역직렬화','샤딩','캐싱'],0,'정규화는 함수 종속성 등을 기준으로 관계를 분해해 중복과 이상 현상을 줄입니다.'),
 {id:'db-5',course:'db',topic:4,type:'short',status:'approved',prompt:'SQL에서 조회할 행의 조건을 지정하는 절의 이름은?',accepted:['where','where절'],model:'WHERE',explanation:'WHERE 절은 결과에 포함할 행을 조건으로 제한합니다.',source:'체험용 자체 작성 문항'},
 {...q('pending-1','os',4,'모든 자원을 한 번에 요청하도록 하면 교착 상태의 어떤 조건을 방지할 수 있나요?', ['점유와 대기','상호 배제','비선점','순환 대기만'],0,'자원을 가진 채 다른 자원을 기다리는 상황을 막으므로 점유와 대기 조건을 방지합니다.'),status:'pending'},
 {...q('pending-2','os',3,'페이지 폴트가 발생했다는 것은 무엇을 의미할까요?', ['프로그램이 항상 종료된다','요청한 페이지가 현재 주기억장치에 없다','CPU가 고장났다','모든 페이지가 캐시에 있다'],1,'요청한 가상 페이지가 현재 물리 메모리에 없으면 페이지 폴트가 발생해 운영체제의 처리가 필요합니다.'),status:'pending'}], history:[], reviewDue:{}, subscriptionUntil:null
};}
export function topicNames(courseId){return courseId==='os'?topics:courseId==='db'?['키와 무결성','SQL과 조인','트랜잭션','정규화','SQL 기초']:[];}
export function hasAccess(state,course){return course.entitled || (state.subscriptionUntil && state.subscriptionUntil>Date.now());}
export function questionBank(state,id){return state.questions.filter(q=>q.course===id&&q.status==='approved');}
export function selectQuiz(state,courseId,weak=false){const course=state.courses.find(c=>c.id===courseId);if(!course)throw Error('과목을 찾을 수 없어요.');if(!hasAccess(state,course))throw Error('이용권을 먼저 선택해 주세요.');const bank=questionBank(state,courseId);if(bank.length<5)throw Error(`아직 풀 수 있는 문항이 부족해요 (현재 ${bank.length}개).`);return [...bank].sort((a,b)=>weak?course.mastery[a.topic]-course.mastery[b.topic]:0).slice(0,weak?5:10);}
export function scoreAnswer(question,answer){if(question.type==='choice')return Number.isInteger(answer)&&answer===question.correct;const clean=String(answer??'').toLowerCase().replace(/[\s()._-]/g,'');return clean.length>0&&question.accepted.some(a=>clean===a.toLowerCase().replace(/[\s()._-]/g,''));}
export function applyResult(state,courseId,responses,now=Date.now()){const course=state.courses.find(c=>c.id===courseId);const before=[...course.mastery];for(const r of responses){const question=state.questions.find(q=>q.id===r.questionId);const i=question.topic;course.mastery[i]=Math.max(0,Math.min(1,course.mastery[i]+(r.correct ? 0.1 : -0.1)));state.reviewDue[courseId+':'+i]=now+(r.correct?86400000:600000);}const result={id:'attempt-'+now+'-'+state.history.length,courseId,at:now,responses,before,after:[...course.mastery],score:Math.round(100*responses.filter(r=>r.correct).length/responses.length)};state.history.unshift(result);return result;}
export function purchase(state,courseId,plan,success=true,now=Date.now()){const c=state.courses.find(c=>c.id===courseId);if(!c)throw Error('과목을 찾을 수 없어요.');if(hasAccess(state,c))throw Error('이미 이용권이 있어요.');if(!['course','subscription'].includes(plan))throw Error('이용권을 선택해 주세요.');if(!success)throw Error('모의 결제에 실패했어요. 다시 시도해 주세요.');if(plan==='course')c.entitled=true;else state.subscriptionUntil=now+30*86400000;}
export function reviewQuestion(state,id,action){const target=state.questions.find(q=>q.id===id);if(!target)throw Error('문항을 찾을 수 없어요.');if(action==='approved'){const normalize=s=>s.trim().replace(/\s+/g,' ');const duplicate=state.questions.find(q=>q.id!==id&&q.course===target.course&&q.status==='approved'&&normalize(q.prompt)===normalize(target.prompt));if(duplicate)throw Error('중복: 문항 '+duplicate.id+'와 동일해요.');}if(!['approved','rejected','deleted'].includes(action))throw Error('잘못된 검수 상태예요.');target.status=action;}
