import test from 'node:test';
import assert from 'node:assert/strict';
import {initialState,selectQuiz,scoreAnswer,applyResult,purchase,reviewQuestion,questionBank,topicNames} from '../core.js';

test('승인 문항으로 퀴즈 구성, 유형과 이용권 검사',()=>{const s=initialState();const quiz=selectQuiz(s,'os');assert.equal(quiz.length,6);assert.ok(quiz.every(q=>q.status==='approved'));assert.ok(quiz.some(q=>q.type==='short'));assert.throws(()=>selectQuiz(s,'db'),/이용권/);});
test('부분 오답 응시를 채점하고 결과·숙련도·복습 시각 반영',()=>{const s=initialState(),quiz=selectQuiz(s,'os'),now=100000;const responses=quiz.map((q,i)=>({questionId:q.id,correct:scoreAnswer(q,i===0?3:q.type==='choice'?q.correct:'문맥 교환')}));const result=applyResult(s,'os',responses,now);assert.equal(result.score,83);assert.equal(s.history.length,1);assert.equal(Math.round(s.courses[0].mastery[0]*100),45);assert.equal(s.reviewDue['os:0'],now+600000);assert.equal(s.reviewDue['os:1'],now+86400000);assert.equal(result.before[0],.55);});
test('객관식 미선택, 단답 공백·오답 및 정답 표기 처리',()=>{const s=initialState(),short=s.questions.find(q=>q.id==='os-6');assert.equal(scoreAnswer(s.questions[0],null),false);assert.equal(scoreAnswer(short,''),false);assert.equal(scoreAnswer(short,' 문맥 교환 '),true);assert.equal(scoreAnswer(short,'Context Switching'),true);assert.equal(scoreAnswer(short,'문맥 교환이 아니다'),false);});
test('결제 실패·미선택·중복 방지와 과목 잠금 해제',()=>{const s=initialState();assert.throws(()=>purchase(s,'db',null),/선택/);assert.throws(()=>purchase(s,'db','course',false),/실패/);assert.equal(s.courses[1].entitled,false);purchase(s,'db','course');assert.equal(selectQuiz(s,'db').length,5);assert.throws(()=>purchase(s,'db','course'),/이미/);});
test('검수 승인 및 삭제가 다음 퀴즈에 반영되고 중복 승인은 거절',()=>{const s=initialState();reviewQuestion(s,'pending-1','approved');assert.equal(questionBank(s,'os').length,7);s.questions.push({...s.questions[0],id:'duplicate',status:'pending'});assert.throws(()=>reviewQuestion(s,'duplicate','approved'),/중복/);reviewQuestion(s,'pending-1','deleted');assert.equal(questionBank(s,'os').length,6);reviewQuestion(s,'os-1','deleted');reviewQuestion(s,'os-2','deleted');assert.throws(()=>selectQuiz(s,'os'),/부족/);});
test('새 과목에 기존 과목의 개념이 혼입되지 않음',()=>{const s=initialState();s.courses.push({id:'new',mastery:[],entitled:true});assert.deepEqual(topicNames('new'),[]);assert.throws(()=>selectQuiz(s,'new'),/부족/);});
